# Generated by Django 5.0.2 on 2024-02-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_options_alter_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
