# Generated by Django 5.0.2 on 2024-02-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_meal_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
