"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-icc#o6d5b)-lt$&cq#+%f*1enls7f69mto8y1msi^bzya!9u@6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "corsheaders",
    'django.contrib.staticfiles',
    "rest_framework",
    "rest_framework.authtoken",
    "users",
    "meals",
    "categories",
    "referals",
    "addresses",
    "payments",
    "orders"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.joinpath("templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


DATABASES = {
'default': {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'NAME': "db_lm59", 
    'USER': "db_lm59_user",
    'PASSWORD':"N9aZXJR4w44zTTOD0vioIIZFXrrXkMax",
    'HOST':"dpg-d0npa16mcj7s73f7vumg-a", 
    'PORT': "5432",
}
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],

    'DEFAULT_PAGINATION_CLASS':
    'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL ="users.User"

CORS_ALLOW_ALL_ORIGINS = True

AWS_ACCESS_KEY_ID = "AKIAQXZDR553VZ447CO4"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_ACL = None
AWS_STORAGE_BUCKET_NAME = "saharakitchen"
AWS_S3_CUSTOM_DOMAIN = "%s.s3.amazonaws.com" % AWS_STORAGE_BUCKET_NAME
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}
AWS_LOCATION = "static"

AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}
AWS_LOCATION = "static"


STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
DEFAULT_FROM_EMAIL = "OptimaInvestment <support@paynexinvestment.com>"
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"


STRIPE_PK="pk_test_51OjMOYGuqI7LdGEkupr9c2Z6JiIbDZvFj4qa2yY9pbyLt964o9gBYsLNsJNdFFfBDN7s1KgjOoxcnjVkRfRqpbYv00KQRxXC7u"
STRIPE_SK="sk_test_51OjMOYGuqI7LdGEkeLS21uYQlwKFvE6OvuTVYYjQFPFjXx8QeZqIE5oniHj0gEVIU3hMg4kREmmXhTBHgxqIOJhY00TGjOto9v"


# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.mailgun.org"
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = True
# EMAIL_PORT = 465
# DEFAULT_FROM_EMAIL = "saharakitchen<postmaster@jobofa.com>"
# EMAIL_HOST_USER = "postmaster@jobofa.com"
# EMAIL_HOST_PASSWORD ="gODFATHERTINZ1@"



# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.mailersend.net"
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# DEFAULT_FROM_EMAIL = "saharakitchen<MS_kDLPfu@trial-351ndgwmvxqlzqx8.mlsender.net>"
# EMAIL_HOST_USER = "MS_kDLPfu@trial-351ndgwmvxqlzqx8.mlsender.net"
# EMAIL_HOST_PASSWORD ="D6gHs4Htn2pMt8vg"


EMAIL_HOST = "smtp.mailgun.org"
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_PORT = 465
DEFAULT_FROM_EMAIL = "SaharaKitchen<admin@saharakitchen.co.uk>"
EMAIL_HOST_USER = "admin@saharakitchen.co.uk"
EMAIL_HOST_PASSWORD ="gODFATHERTINZ1@"




# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.mailersend.net"
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# DEFAULT_FROM_EMAIL = "saharakitchen<MS_MJedBt@saharakitchen.co.uk>"
# EMAIL_HOST_USER = "MS_MJedBt@saharakitchen.co.uk"
# EMAIL_HOST_PASSWORD ="8qX02ewUYzMGLqyn"
FRONTEND_URL="https://saharakitchen.co.uk/"


SQUARE_ACCESS_TOKEN = 'EAAAl_w4MVWrclcimDAfORzmX_wOJp6PIaxCjVoJ1bh1JQrRypK3CRrv8WyPAOFu'
SQUARE_LOCATION_ID = 'L79W2D51FX5JQ'
SQUARE_APPLICATION_ID = 'sq0idp-sEdY2YnkKafEVxUcjzq1zw'
SQUARE_ENVIRONMENT = 'production'  # Use 'production' for live environment
