# Generated by Django 4.2.6 on 2023-11-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referal',
            name='recieved',
            field=models.BooleanField(default=False),
        ),
    ]
