# Generated by Django 5.0.2 on 2024-02-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_options_alter_meal_category'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(blank=True, null=True, to='meals.meal'),
        ),
    ]
