# Generated by Django 5.0.2 on 2024-02-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_options_alter_meal_category'),
        ('orders', '0002_remove_order_food_order_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.AddField(
            model_name='order',
            name='foods',
            field=models.ManyToManyField(to='meals.meal'),
        ),
    ]
