# Generated by Django 5.0.2 on 2024-02-16 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_options_alter_meal_category'),
        ('orders', '0003_remove_order_food_order_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='foods',
        ),
        migrations.CreateModel(
            name='OrderQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantites', to='meals.meal')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quantities',
            field=models.ManyToManyField(to='orders.orderquantity'),
        ),
    ]
