# Generated by Django 5.0.2 on 2024-02-16 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_options_alter_meal_category'),
        ('orders', '0004_remove_order_foods_orderquantity_order_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderquantity',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal'),
        ),
    ]
