# Generated by Django 5.0.2 on 2024-02-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderquantity_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pay_on_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
