# Generated by Django 5.0.2 on 2026-05-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.TextField(blank=True, null=True),
        ),
    ]
